"""Add unique constraint on feedback message_id

Revision ID: 13f9da3db90d
Revises: 6dcbfcd576d3
Create Date: 2025-01-28 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f9da3db90d'
down_revision: Union[str, Sequence[str], None] = '6dcbfcd576d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add unique constraint to feedback.message_id to prevent duplicate feedback."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_feedback_message_id', 'feedback', ['message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove unique constraint from feedback.message_id."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_feedback_message_id', 'feedback', type_='unique')
    # ### end Alembic commands ###