"""Initial migration: add conversations and messages tables

Revision ID: 77ffb8af086d
Revises: 928e3480ac21
Create Date: 2025-07-16 13:47:03.010886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ffb8af086d'
down_revision: Union[str, Sequence[str], None] = '928e3480ac21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('account_id', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_conversations_wallet_address'), table_name='conversations')
    op.create_index(op.f('ix_conversations_account_id'), 'conversations', ['account_id'], unique=False)
    op.drop_column('conversations', 'wallet_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('wallet_address', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_conversations_account_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_wallet_address'), 'conversations', ['wallet_address'], unique=False)
    op.drop_column('conversations', 'account_id')
    # ### end Alembic commands ###
