"""Add suggested_queries table

Revision ID: ad6886ff187a
Revises: 77ffb8af086d
Create Date: 2025-07-17 17:26:49.222964

"""
import uuid

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6886ff187a'
down_revision: Union[str, Sequence[str], None] = '77ffb8af086d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggested_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('context', sa.Enum('ANONYMOUS', 'CONNECTED', name='suggestion_context_enum'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggested_queries_context'), 'suggested_queries', ['context'], unique=False)
    # ### end Alembic commands ###
    
    # Seed data for suggested queries
    from sqlalchemy.sql import table, column
    from sqlalchemy import String, Integer, Enum as DBEnum
    from sqlalchemy.dialects.postgresql import UUID

    
    suggested_queries_table = table('suggested_queries',
        column('id', UUID),
        column('query', String),
        column('context', DBEnum(name='suggestion_context_enum')),
        column('display_order', Integer)
    )
    
    # Define the seed data
    seed_data = [
        # Anonymous queries
        {'id': '550e8400-e29b-41d4-a716-446655440001', 'query': 'What is the current price of HBAR?', 'context': 'ANONYMOUS', 'display_order': 1},
        {'id': '550e8400-e29b-41d4-a716-446655440002', 'query': 'What happened in transaction 0.0.12345@1750376965.638444236?', 'context': 'ANONYMOUS', 'display_order': 2},
        {'id': '550e8400-e29b-41d4-a716-446655440003', 'query': 'Show recent activity for wallet 0.0.98', 'context': 'ANONYMOUS', 'display_order': 3},
        {'id': '550e8400-e29b-41d4-a716-446655440004', 'query': 'What are the latest transactions on the Hedera network?', 'context': 'ANONYMOUS', 'display_order': 4},
        # Connected queries
        {'id': '550e8400-e29b-41d4-a716-446655440005', 'query': 'What tokens do I currently hold?', 'context': 'CONNECTED', 'display_order': 1},
        {'id': '550e8400-e29b-41d4-a716-446655440006', 'query': 'Show my last 5 transactions', 'context': 'CONNECTED', 'display_order': 2},
        {'id': '550e8400-e29b-41d4-a716-446655440007', 'query': 'What is the total value of my wallet?', 'context': 'CONNECTED', 'display_order': 3},
        {'id': '550e8400-e29b-41d4-a716-446655440008', 'query': 'Show my NFT collection', 'context': 'CONNECTED', 'display_order': 4},
    ]
    
    op.bulk_insert(suggested_queries_table, seed_data)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggested_queries_context'), table_name='suggested_queries')
    op.drop_table('suggested_queries')
    # ### end Alembic commands ###
