"""Add suggested_queries table

Revision ID: ad6886ff187a
Revises: 928e3480ac21
Create Date: 2025-07-17 17:26:49.222964

"""
import uuid

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad6886ff187a'
down_revision: Union[str, Sequence[str], None] = '928e3480ac21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggested_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('context', sa.Enum('ANONYMOUS', 'CONNECTED', name='suggestion_context_enum'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggested_queries_context'), 'suggested_queries', ['context'], unique=False)
    # ### end Alembic commands ###
    
    # Seed data for suggested queries
    from sqlalchemy.sql import table, column
    from sqlalchemy import String, Integer, Enum as DBEnum, DateTime
    from sqlalchemy.dialects.postgresql import UUID

    
    suggested_queries_table = table('suggested_queries',
        column('id', UUID),
        column('query', String),
        column('context', DBEnum(name='suggestion_context_enum')),
        column('display_order', Integer),
        column('created_at', DateTime(timezone=True)),
        column('updated_at', DateTime(timezone=True))
    )
    
    # Define the seed data
    seed_data = [
        # Anonymous queries
        {'id': '550e8400-e29b-41d4-a716-446655440001', 'query': 'What is the price of 1 HBAR at the moment?', 'context': 'ANONYMOUS', 'display_order': 1},
        {'id': '550e8400-e29b-41d4-a716-446655440002', 'query': 'Please explain transaction 0.0.4686511@1709237346.000000000', 'context': 'ANONYMOUS', 'display_order': 2},
        {'id': '550e8400-e29b-41d4-a716-446655440003', 'query': 'Show me the last 3 transactions for account 0.0.5947117', 'context': 'ANONYMOUS', 'display_order': 3},
        {'id': '550e8400-e29b-41d4-a716-446655440004', 'query': 'Summarize the assets of 0.0.4904246', 'context': 'ANONYMOUS', 'display_order': 4},
        {'id': '550e8400-e29b-41d4-a716-446655440005', 'query': 'Did transaction 0.0.995584@1750920389.856235105 go through?', 'context': 'ANONYMOUS', 'display_order': 5},
    ]
    
    op.bulk_insert(suggested_queries_table, seed_data)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggested_queries_context'), table_name='suggested_queries')
    op.drop_table('suggested_queries')
    # ### end Alembic commands ###
